1.2.0 Compatibility with 3.0 form
LinkNacional/fee-recovery-for-givewp pull request #14
Opened 2024-07-23 20:34 UTC by Abraao2005

# 1.2.0 - 23/07/2024
* Compatibility with Form 3.0

# 1.1.2 - 02/01/2024
* Fix security issues with plugin;
* Fix internationalization.

# 1.1.1 - 28/12/2023
* Remove security vulnerabilities;
* Compatibility with WordPress 6.4;
* Update license with GPLv3.

# 1.1.0 - 18/08/2023
* Plugin percent fee option now accept float values;
* After the checkbox is marked the total amount is updated with fees;
* Dinamically change the currency symbol;
* Adds compatibility with any currency;
* Fixed a bug in fee calculation for numbers in the thousands.

# 1.0.0 - 21/07/2023
* Plugin launch.

2024-07-26 17:58 UTC, GuilhermeLinkNacional requested changes
Quando colocamos um valor com decimal nas taxas, no frontend o valor é arredondado para número inteiro, nessa imagem eu coloquei 1.5
![image](https://github.com/user-attachments/assets/db6c60a4-b541-49ad-a35d-6e8b33604cbb)

2024-07-26 18:07 UTC, Abraao2005 commented
> Quando colocamos um valor com decimal nas taxas, no frontend o valor é arredondado para número inteiro, nessa imagem eu coloquei 1.5 ![image](https://private-user-images.githubusercontent.com/161341491/352620608-db6c60a4-b541-49ad-a35d-6e8b33604cbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTczODgsIm5iZiI6MTcyMjAxNzA4OCwicGF0aCI6Ii8xNjEzNDE0OTEvMzUyNjIwNjA4LWRiNmM2MGE0LWI1NDEtNDlhZC1hMzVkLTZlOGIzMzYwNGNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxODA0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmRhODkxZTVjZmJhOGZkNjM5MTM3ZjJlNWRmYWU5NDUxNTE5ZDU1NzQ2Njc4MjczNDg1YjFlMzg4MjZmM2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dRvJ6Y-A6GFz2f04Dhc-APXP3i4VuynxesiKtpkt2iQ)

![image](https://github.com/user-attachments/assets/04f2d4a9-cce3-4e9f-935d-faebd3c8fa24)
No meu está funcionando
Veja se você ativou nas configurações do givewp os decimais

2024-07-26 19:11 UTC, GuilhermeLinkNacional approved these changes

2024-12-14 21:29 UTC, emanuellopess approved these changes

2024-12-14 21:29 UTC, merged